name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]
env:
  PROJECT: countries-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.RUN_PROJECT}}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: CountriesDEV
          runtime: java17
          project_id: countries-api
          entry_point: functions.CountriesDEV

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding ILoveMkdev --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"
